include .env
export

export PROJECT_ROOT=$(shell pwd)



DB_URL = postgresql://${PG_USER}:${PG_PASS}@db:${PG_PORT}/${PG_DB}?sslmode=disable


migrations-up:
	docker compose run --rm migrate \
		-source file:///migrations \
		-database $(DB_URL) up

migrations-down:
	docker compose run --rm migrate \
		-source file:///migrations \
		-database $(DB_URL) down